### ISSUE TITLE
References, many CMS table field value not comes to response... 

### ISSUE THREAD

**Issue by AshishPatel48** [contentful/discovery-app#3]
![screen shot 2017-10-26 at 12 02 32 pm](https://user-images.githubusercontent.com/30335874/32038000-9a2a4904-ba45-11e7-9b8d-a3e83418ba23.png)

(iOS Programming)
Hi 
I have one table and and one field have References - many, and one file have References - single.
I got fields of single References but didn't got References - many filed.

Getting value of : Reference body part
But do not : reference nutrition 

can you please help how to get reference nutrition value?

**Comment by loudmouth** [comment]
This repo is being deprecated
